/**
 * @file signal_processing.c
 * @brief Implementation of FIR and Complementary filters for IMU data.
 */
#include "signal_processing.h"
#include <string.h> // For memset
#include <math.h>   // For atan2f, sqrtf

#ifndef M_PI
#define M_PI 3.14159265358979323846f
#endif

/*
 * 1. FIR low-pass coefficients (generated by Tools/generate_fir.py).
 *    Design: 31-tap Hamming-window low-pass, fs = 500 Hz, cutoff = 5 Hz.
 *    Symmetric (linear phase); sum ~= 1.0 (unity DC gain).
 *    Regenerate after any change to the IMU sample rate (SMPLRT_DIV/DLPF).
 */
const float FIR_COEFFS_LOWPASS[FIR_TAPS] = {
    0.004322f, 0.004964f, 0.006727f, 0.009591f, 0.013477f, 0.018251f,
    0.023725f, 0.029671f, 0.035828f, 0.041920f, 0.047666f, 0.052795f,
    0.057065f, 0.060272f, 0.062260f, 0.062933f, 0.062260f, 0.060272f,
    0.057065f, 0.052795f, 0.047666f, 0.041920f, 0.035828f, 0.029671f,
    0.023725f, 0.018251f, 0.013477f, 0.009591f, 0.006727f, 0.004964f,
    0.004322f
};

/*
 * Gyroscope sensitivity for the default +/-250 dps full-scale range
 * (MPU_GYRO_CFG left at 0x00 in IMU_Init): 131 LSB per deg/s.
 * Raw counts are divided by this to obtain deg/s before integration.
 */
#define GYRO_SENS_250DPS 131.0f
#define RAD_TO_DEG (180.0f / M_PI)

/* ====================================================================
 * Function Implementations
 * ==================================================================== */

/**
 * @brief Initializes the IMU processing state.
 * Clears all FIR filter history buffers to zero and resets the 
 * complementary filter attitude angles.
 * 
 * @param state Pointer to the IMU processing state to initialize.
 */
void SignalProcessing_Init(IMU_ProcessingState* state) {
    /* memset(0) clears both history[] and head for every channel at once,
       since the whole struct is plain floats/ints. */
    memset(state, 0, sizeof(*state));
}

/**
 * @brief Executes a single iteration of the FIR filter using a ring buffer.
 * 
 * @param state Pointer to the specific FIR filter state.
 * @param input The latest raw sensor sample.
 * @param coeffs Pointer to the array of filter coefficients.
 * @return float The filtered output.
 */
float FIR_ProcessSingle(FIR_FilterState* state, float input, const float* coeffs) {
    /* Store the newest sample at the head of the ring buffer. */
    state->history[state->head] = input;

    /* Convolve: y[n] = sum_{k=0}^{TAPS-1} coeffs[k] * x[n-k].
       Walk backwards from head so coeffs[0] multiplies the newest sample. */
    float acc = 0.0f;
    int idx = state->head;
    for (int k = 0; k < FIR_TAPS; k++) {
        acc += coeffs[k] * state->history[idx];
        if (--idx < 0) {
            idx = FIR_TAPS - 1;
        }
    }

    /* Advance head for the next sample, wrapping around. */
    if (++state->head >= FIR_TAPS) {
        state->head = 0;
    }

    return acc;
}

/**
 * @brief Calculates the current pitch and roll using a complementary filter.
 * Combines high-frequency gyroscope data (integrated for short-term accuracy)
 * and low-frequency accelerometer data (for long-term stability).
 * 
 * @param state Pointer to the complementary filter state.
 * @param acc_x Filtered X-axis accelerometer data.
 * @param acc_y Filtered Y-axis accelerometer data.
 * @param acc_z Filtered Z-axis accelerometer data.
 * @param gyro_x Filtered X-axis gyroscope data (pitch rate).
 * @param gyro_y Filtered Y-axis gyroscope data (roll rate).
 * @param dt Sampling interval in seconds.
 */
void Complementary_Process(Complementary_FilterState* state, 
                           float acc_x, float acc_y, float acc_z, 
                           float gyro_x, float gyro_y, 
                           float dt) {
    /* Accelerometer gives an absolute (drift-free but noisy) tilt estimate.
       atan2f uses ratios, so raw LSB counts work directly — no need to
       convert to g. Axis mapping assumes the board's convention where
       pitch = rotation about X, roll = rotation about Y; adjust the axes
       here if your mounting differs.
       gyro_x / gyro_y must already be in deg/s (see SignalProcessing_Update). */
    float acc_pitch = atan2f(acc_y, sqrtf(acc_x * acc_x + acc_z * acc_z)) * RAD_TO_DEG;
    float acc_roll  = atan2f(-acc_x, sqrtf(acc_y * acc_y + acc_z * acc_z)) * RAD_TO_DEG;

    /* Complementary filter: trust the integrated gyro for fast motion
       (high-pass), correct slow drift with the accelerometer (low-pass). */
    state->pitch = COMPLEMENTARY_ALPHA * (state->pitch + gyro_x * dt)
                 + (1.0f - COMPLEMENTARY_ALPHA) * acc_pitch;
    state->roll  = COMPLEMENTARY_ALPHA * (state->roll  + gyro_y * dt)
                 + (1.0f - COMPLEMENTARY_ALPHA) * acc_roll;
}

/**
 * @brief Main processing pipeline for a new set of IMU readings.
 * 
 * @param state Pointer to the overall IMU processing state.
 * @param raw_ax Raw X accelerometer data.
 * @param raw_ay Raw Y accelerometer data.
 * @param raw_az Raw Z accelerometer data.
 * @param raw_gx Raw X gyroscope data.
 * @param raw_gy Raw Y gyroscope data.
 * @param raw_gz Raw Z gyroscope data.
 * @param dt Sampling time delta.
 */
void SignalProcessing_Update(IMU_ProcessingState* state, 
                             float raw_ax, float raw_ay, float raw_az, 
                             float raw_gx, float raw_gy, float raw_gz,
                             float dt) {
    /* 1. Low-pass filter every axis independently. */
    float ax = FIR_ProcessSingle(&state->acc_x_filter,  raw_ax, FIR_COEFFS_LOWPASS);
    float ay = FIR_ProcessSingle(&state->acc_y_filter,  raw_ay, FIR_COEFFS_LOWPASS);
    float az = FIR_ProcessSingle(&state->acc_z_filter,  raw_az, FIR_COEFFS_LOWPASS);
    float gx = FIR_ProcessSingle(&state->gyro_x_filter, raw_gx, FIR_COEFFS_LOWPASS);
    float gy = FIR_ProcessSingle(&state->gyro_y_filter, raw_gy, FIR_COEFFS_LOWPASS);
    (void)FIR_ProcessSingle(&state->gyro_z_filter, raw_gz, FIR_COEFFS_LOWPASS);

    /* Cache filtered accelerometer outputs for inspection. */
    state->filt_acc_x = ax;
    state->filt_acc_y = ay;
    state->filt_acc_z = az;

    /* 2. Convert filtered gyro counts to deg/s before fusing. */
    float gx_dps = gx / GYRO_SENS_250DPS;
    float gy_dps = gy / GYRO_SENS_250DPS;

    /* 3. Update attitude estimate (pitch/roll). */
    Complementary_Process(&state->attitude, ax, ay, az, gx_dps, gy_dps, dt);

    /* 4. Feed the filtered accel into the gesture recognizer (per sample). */
    state->last_gesture = Gesture_ProcessSample(&state->gesture, ax, ay, az);
}

/* ====================================================================
 * Gesture recognition (rule-based shake detector)
 * ==================================================================== */

/* Internal state-machine values for GestureState.state. */
enum { GST_IDLE = 0, GST_ACTIVE, GST_COOLDOWN };

void Gesture_Init(GestureState* g) {
    memset(g, 0, sizeof(*g));   /* state = GST_IDLE, grav_init = 0 */
}

const char* Gesture_Name(GestureType t) {
    switch (t) {
        case GESTURE_SHAKE_X: return "SHAKE FWD-BACK (X)";
        case GESTURE_SHAKE_Y: return "SHAKE LEFT-RIGHT (Y)";
        case GESTURE_SHAKE_Z: return "SHAKE UP-DOWN (Z)";
        default:              return "NONE";
    }
}

/* Classify the just-finished gesture from the accumulated AC energy and
   zero-crossing counts. Returns GESTURE_NONE if it fails the sanity checks. */
static GestureType gesture_classify(const GestureState* g) {
    if (g->active_count < GESTURE_MIN_LEN) {
        return GESTURE_NONE;   /* too short — likely a bump, not a shake */
    }

    /* Dominant axis = the one with the most AC energy. */
    GestureType type;
    int zc;
    if (g->energy_x >= g->energy_y && g->energy_x >= g->energy_z) {
        type = GESTURE_SHAKE_X; zc = g->zc_x;
    } else if (g->energy_y >= g->energy_z) {
        type = GESTURE_SHAKE_Y; zc = g->zc_y;
    } else {
        type = GESTURE_SHAKE_Z; zc = g->zc_z;
    }

    /* Require real oscillation on the dominant axis (rules out a single
       push/tap, which has too few direction reversals). */
    if (zc < GESTURE_MIN_ZC) {
        return GESTURE_NONE;
    }
    return type;
}

GestureType Gesture_ProcessSample(GestureState* g, float ax, float ay, float az) {
    /* Track gravity (DC) with a slow EMA, then work on the AC residual so
       static tilt never triggers a gesture. */
    if (!g->grav_init) {
        g->grav_x = ax; g->grav_y = ay; g->grav_z = az;
        g->grav_init = 1;
    } else {
        g->grav_x = GRAV_ALPHA * g->grav_x + (1.0f - GRAV_ALPHA) * ax;
        g->grav_y = GRAV_ALPHA * g->grav_y + (1.0f - GRAV_ALPHA) * ay;
        g->grav_z = GRAV_ALPHA * g->grav_z + (1.0f - GRAV_ALPHA) * az;
    }

    float acx = ax - g->grav_x;
    float acy = ay - g->grav_y;
    float acz = az - g->grav_z;
    float mag = sqrtf(acx * acx + acy * acy + acz * acz);

    GestureType result = GESTURE_NONE;

    switch (g->state) {
        case GST_IDLE:
            if (mag > GESTURE_ONSET_LSB) {
                /* Start of a gesture: reset accumulators. */
                g->state = GST_ACTIVE;
                g->active_count = 0;
                g->energy_x = g->energy_y = g->energy_z = 0.0f;
                g->zc_x = g->zc_y = g->zc_z = 0;
                g->prev_ac_x = g->prev_ac_y = g->prev_ac_z = 0.0f;
            }
            break;

        case GST_ACTIVE:
            g->active_count++;

            /* Accumulate per-axis energy. */
            g->energy_x += acx * acx;
            g->energy_y += acy * acy;
            g->energy_z += acz * acz;

            /* Count sign changes (zero-crossings) = oscillation evidence. */
            if (acx * g->prev_ac_x < 0.0f) g->zc_x++;
            if (acy * g->prev_ac_y < 0.0f) g->zc_y++;
            if (acz * g->prev_ac_z < 0.0f) g->zc_z++;
            g->prev_ac_x = acx;
            g->prev_ac_y = acy;
            g->prev_ac_z = acz;

            /* End when motion settles (hysteresis) or we hit the time cap. */
            if (mag < GESTURE_OFFSET_LSB || g->active_count >= GESTURE_MAX_LEN) {
                result = gesture_classify(g);
                g->state = GST_COOLDOWN;
                g->cooldown_count = 0;
            }
            break;

        case GST_COOLDOWN:
            if (++g->cooldown_count >= GESTURE_COOLDOWN) {
                g->state = GST_IDLE;
            }
            break;

        default:
            g->state = GST_IDLE;
            break;
    }

    return result;
}

// ====================================================================
// Placeholders for future Machine Learning feature extraction
// ====================================================================
void SignalProcessing_ExtractFeatures(float* input, float* features) {
    // To be implemented later for ML pipeline
}

void SignalProcessing_OnsetDetection(float* input, int* onset_detected) {
    // To be implemented later for gesture start/end detection
}
